before:
  hooks:
    - go mod download

builds:
  - id: pronestheus
    main: ./cmd/pronestheus/main.go
    binary: pronestheus
    ldflags:
      - -s -w 
      - -X main.version={{.Version}} 
      - -X main.commit={{.Commit}} 
      - -X main.date={{.Date}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64


archives:
  - id: archive
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    # Don't include any additional files into the archives (such as README, CHANGELOG etc). 
    files:
      - none* 

checksum:
  name_template: 'checksums.txt'

changelog:
  skip: true

release:
  github:
    owner: iveney
    name: pronestheus

dockers:
  - dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    image_templates:
      - "ivansiu/pronestheus:{{ .Tag }}"
      - "ivansiu/pronestheus:latest"

nfpms:
  - license: MIT
    maintainer: iveney
    homepage: https://github.com/iveney/pronestheus
    bindir: /usr/local/bin
    description: Prometheus exporter for the Nest Learning Thermostat
    formats:
      - deb
      - rpm
