name: build

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.16'
      - name: Run go test
        run: CGO_ENABLED=0 GOOS=linux go test ./... -v
